version: '3.8'

services:
  ## apiserver
  apiserver:
    build:
      context: server/
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DB_PORT=3306
      - DB_HOST=todo-db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=todomini
    volumes:
      - ${PWD}/logs:/usr/src/app/logs
    depends_on:
      - todo-db
    networks:
      - common-bridge
    logging:
      options:
        max-size: 5k
        max-file: '3'

  ## Mysql
  todo-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=todomini
    ports:
      - '3306:3306'
    networks:
      - common-bridge

networks:
  common-bridge:
    driver: bridge
