version: '3.8'

services:
  node-todo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - DB_PORT=3306
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=todomini
    volumes:
      - ${PWD}/outlogs:/usr/src/app/logs
    depends_on:
      - mysql
    networks:
      - todo-network
    logging:
      options:
        max-size: 5k
        max-file: '3'

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=todomini
    ports:
      - '3306:3306'
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
